devtools::install_github('chris-mcginnis-ucsf/DoubletFinder')
library(Seurat)
library(tidyverse)
library(readxl)
library(viridis)
library(ggrepel)
library(vegan)
library(ggpubr)
library(RaceID)
library(Seurat)
library(tidyverse)
library(assertthat)
library(FateID)
library(readxl)
library(limma)
library(MASS)

#setup the folders
dir.create("data")
dir.create("R")
dir.create("plots")
dir.create(file.path("plots", "umap"))
dir.create(file.path("plots", "heatmaps"))
dir.create(file.path("plots", "others"))
